/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DlExtractionTermDto } from './dlExtractionTermDto';


export interface DlExtractionDonePayload {
    whItemId?: number;
    terms?: Array<DlExtractionTermDto>;
    suggestedTerm?: string | null;
}

