/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LookupResponse { 
    lookupStatus?: LookupResponse.LookupStatusEnum;
    quickFacts?: { [key: string]: string; };
    icecatId?: string;
    icecatSpecsJson?: string;
}
export namespace LookupResponse {
    export const LookupStatusEnum = {
        Complete: 'COMPLETE',
        Failed: 'FAILED',
        QuotaExceeded: 'QUOTA_EXCEEDED'
    } as const;
    export type LookupStatusEnum = typeof LookupStatusEnum[keyof typeof LookupStatusEnum];
}


