/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LookupResponse { 
    lookupStatus?: LookupResponse.LookupStatusEnum;
    quickFacts?: { [key: string]: string; };
    icecatId?: string;
    icecatSpecsJson?: string;
    sourceType?: LookupResponse.SourceTypeEnum;
    sourceDomain?: string;
    siteLabel?: string;
    sourceUrl?: string;
    featureGroupsJson?: string;
}
export namespace LookupResponse {
    export const LookupStatusEnum = {
        Complete: 'COMPLETE',
        Failed: 'FAILED',
        QuotaExceeded: 'QUOTA_EXCEEDED'
    } as const;
    export type LookupStatusEnum = typeof LookupStatusEnum[keyof typeof LookupStatusEnum];
    export const SourceTypeEnum = {
        Icecat: 'ICECAT',
        Flatpanelshd: 'FLATPANELSHD',
        Gsmarena: 'GSMARENA',
        Generic: 'GENERIC'
    } as const;
    export type SourceTypeEnum = typeof SourceTypeEnum[keyof typeof SourceTypeEnum];
}


