/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LookupHistoryEntryDto { 
    lookupTerm?: string;
    lookupStatus?: LookupHistoryEntryDto.LookupStatusEnum;
    quickFacts?: { [key: string]: string; };
    icecatId?: string;
    sourceType?: LookupHistoryEntryDto.SourceTypeEnum;
    sourceDomain?: string;
    siteLabel?: string;
    sourceUrl?: string;
    featureGroupsJson?: string;
    createdAt?: string;
}
export namespace LookupHistoryEntryDto {
    export const LookupStatusEnum = {
        Complete: 'COMPLETE',
        Failed: 'FAILED',
        QuotaExceeded: 'QUOTA_EXCEEDED',
        NoSources: 'NO_SOURCES',
        Error: 'ERROR',
        RateLimited: 'RATE_LIMITED'
    } as const;
    export type LookupStatusEnum = typeof LookupStatusEnum[keyof typeof LookupStatusEnum];
    export const SourceTypeEnum = {
        Icecat: 'ICECAT',
        Flatpanelshd: 'FLATPANELSHD',
        Gsmarena: 'GSMARENA',
        Generic: 'GENERIC'
    } as const;
    export type SourceTypeEnum = typeof SourceTypeEnum[keyof typeof SourceTypeEnum];
}


