/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProviderStatus { 
    searchState?: ProviderStatus.SearchStateEnum;
    llmState?: ProviderStatus.LlmStateEnum;
    searchProvider?: string;
    llmProvider?: string;
    searchError?: string;
    llmError?: string;
    searchHttpStatus?: number;
    llmHttpStatus?: number;
    serverStartToken?: string;
}
export namespace ProviderStatus {
    export const SearchStateEnum = {
        Unconfigured: 'UNCONFIGURED',
        Configured: 'CONFIGURED',
        Valid: 'VALID',
        Unreachable: 'UNREACHABLE',
        Unavailable: 'UNAVAILABLE'
    } as const;
    export type SearchStateEnum = typeof SearchStateEnum[keyof typeof SearchStateEnum];
    export const LlmStateEnum = {
        Unconfigured: 'UNCONFIGURED',
        Configured: 'CONFIGURED',
        Valid: 'VALID',
        Unreachable: 'UNREACHABLE',
        Unavailable: 'UNAVAILABLE'
    } as const;
    export type LlmStateEnum = typeof LlmStateEnum[keyof typeof LlmStateEnum];
}


