/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuercheckerListingDto { 
    id?: number;
    whId?: string;
    title?: string;
    description?: string;
    price?: number;
    location?: string;
    url?: string;
    listedAt?: string;
    fetchedAt?: string;
    thumbnailUrl?: string;
    hasNote?: boolean;
    viewCount?: number;
    lastViewedAt?: string;
    rating?: string;
}

