/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SetupFieldDto } from './setupFieldDto';


export interface SetupProviderDto { 
    name?: string;
    label?: string;
    fields?: Array<SetupFieldDto>;
}

