/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProviderUsageDto } from './providerUsageDto';


export interface UsageResponse { 
    brave?: ProviderUsageDto;
    groq?: ProviderUsageDto;
    openRouter?: ProviderUsageDto;
}

