/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelUsageDto } from './modelUsageDto';
import { ProviderUsageDto } from './providerUsageDto';


export interface UsageResponse { 
    activeSearchProvider?: string;
    activeLlmProvider?: string;
    brave?: ProviderUsageDto;
    googleDiscovery?: ProviderUsageDto;
    groq?: ProviderUsageDto;
    openRouter?: ProviderUsageDto;
    groqModelBreakdown?: Array<ModelUsageDto>;
}

