/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WhCategoryDto } from './whCategoryDto';
import { WhPreviewDto } from './whPreviewDto';


export interface WhDetailDto { 
    whItemId?: number;
    id?: number;
    whId?: string;
    title?: string;
    price?: number;
    location?: string;
    url?: string;
    listedAt?: string;
    fetchedAt?: string;
    paylivery?: boolean;
    categoryPath?: Array<WhCategoryDto>;
    description?: string;
    previews?: Array<WhPreviewDto>;
    note?: string;
    rating?: string;
    interestLevel?: string;
    tags?: Array<string>;
    viewCount?: number;
    lastViewedAt?: string;
    createdAt?: string;
    updatedAt?: string;
}

