/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WhCategoryDto } from './whCategoryDto';


export interface WhItemDto { 
    id?: number;
    whId?: string;
    title?: string;
    description?: string;
    price?: number;
    location?: string;
    url?: string;
    listedAt?: string;
    fetchedAt?: string;
    thumbnailUrl?: string;
    imageUrls?: Array<string>;
    hasNote?: boolean;
    viewCount?: number;
    lastViewedAt?: string;
    rating?: string;
    interestLevel?: string;
    paylivery?: boolean;
    categoryPath?: Array<WhCategoryDto>;
}

