/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WhListingDetailDto { 
    id?: number;
    whListingId?: number;
    note?: string;
    viewCount?: number;
    lastViewedAt?: string;
    rating?: string;
    interestLevel?: string;
    tags?: Array<string>;
    createdAt?: string;
    updatedAt?: string;
}

