/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WhItemDto } from './whItemDto';


export interface WhSearchResultDto { 
    totalCount?: number;
    listings?: Array<WhItemDto>;
}

