export const API_URLS = {
  health: '/api/health',
  listings: '/api/listings',
  whSearch: '/api/wh/search',
  whLocations: '/api/wh/meta/locations',
  whCategories: '/api/wh/meta/categories',
  sse: (eventSourceId: string) => `/api/sse?eventSourceId=${eventSourceId}`,
  dlExtractionTerms: (whItemId: number) => `/api/dl/extraction/${whItemId}/terms`,
  dlSettings: '/api/dl/settings',
  productSearch: '/api/research/product/search',
  icecatSpec: (ean: string) => `/api/research/icecat/${ean}`,
  productLookup: (listingId: number) => `/api/listings/${listingId}/lookup`,
  productLookupHistory: (listingId: number) => `/api/listings/${listingId}/lookup/history`,
  productFullSpecs: (listingId: number) => `/api/listings/${listingId}/lookup/full-specs`,
  apiUsage: '/api/usage',
  settingsPreferences: '/api/settings/preferences',
  settingsPreferenceCategory: (categoryId: number) => `/api/settings/preferences/${categoryId}`,
  providerStatus: '/api/provider-status',
  authMe: '/api/auth/me',
  authLoginWithKey: '/api/auth/login-with-key',
  authLogout: '/api/auth/logout',
  authGenerateKey: '/api/auth/generate-key',
  authKeys: '/api/auth/keys',
  authKey: (id: number) => `/api/auth/keys/${id}`,
  authKeyRevoke: (id: number) => `/api/auth/keys/${id}/revoke`,
  authKeyUnrevoke: (id: number) => `/api/auth/keys/${id}/unrevoke`,
} as const;
